# example netlify.toml
[build]
  command = "npm i"
  functions = "netlify/functions"
  publish = "."

[dev]
  autoLaunch = false

[functions]
  node_bundler = "esbuild"
  external_node_modules = ["@sparticuz/chromium"]